spring:
  profiles:
    active: local-win
---
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB
  session:
    store-type: jdbc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.hanjulcoding.home
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
logging:
  level:
    com.hanjulcoding.home.domain: TRACE
---
# local 환경
spring:
  profiles: local-win
  devtools:
    restart:
      enabled: true
      additional-paths: classpath:/
    livereload:
      enabled: true
  mustache:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.114.225.200:3306/test?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: jjh0735
server:
  port: 8081
  upload:
    path: D:/upload/