package com.inad.mgr.domain;

import lombok.Data;

@Data
public class BrTitleInfo {
	String mgmBldrgstPk;						//관리_건축물대장_PK
	String regstrGbCd;							//대장_구분_코드
	String regstrGbCdNm;						//대장_구분_코드_명
	String regstrKindCd;						//대장_종류_코드
	String regstrKindCdNm;						//대장_종류_코드_명
	String platPlc;								//대지_위치
	String newPlatPlc;							//도로명_대지_위치
	String bldNm;								//건물_명
	String sigunguCd;							//시군구_코드
	String bjdongCd;							//법정동_코드
	String platGbCd;							//대지_구분_코드
	String bun;									//번
	String ji;									//지
	String splotNm;								//특수지_명
	String block;								//블록
	String lot;									//로트
	String bylotCnt;							//외필지_수
	String naRoadCd;							//새주소_도로_코드
	String naBjdongCd;							//새주소_법정동_코드
	String naUgrndCd;							//새주소_지상지하_코드
	String naMainBun;							//새주소_본_번
	String naSubBun;							//새주소_부_번
	String dongNm;								//동_명
	String mainAtchGbCd;						//주_부속_구분_코드
	String mainAtchGbCdNm;						//주_부속_구분_코드_명
	String platArea;							//대지_면적(㎡)
	String archArea;							//연_면적(㎡)
	String bcRat;								//건폐_율(%)
	String totArea;								//연면적(㎡)
	String vlRatEstmTotArea;					//용적_률_산정_연면적(㎡)
	String vlRat;								//용적_률(%)
	String strctCd;								//구조_코드
	String strctCdNm;							//구조_코드_명
	String etcStrct;							//기타_구조
	String mainPurpsCd;							//주_용도_코드
	String mainPurpsCdNm;						//주_용도_코드_명
	String etcPurps;							//기타_용도
	String roofCd;								//지붕_코드
	String roofCdNm;							//지붕_코드_명
	String etcRoof;								//기타_지붕
	String hhldCnt;								//세대_수(세대)
	String fmlyCnt;								//가구_수(가구)
	String heit;								//높이(m)
	String grndFlrCnt;							//지상_층_수
	String ugrndFlrCnt;							//지하_층_수
	String rideUseElvtCnt;						//승용_승강기_수
	String emgenUseElvtCnt;						//비상용_승강기_수
	String atchBldCnt;							//부속_건축물_수
	String atchBldArea;							//부속_건축물_면적(㎡)
	String totDongTotArea;						//총_동_연면적(㎡)
	String indrMechUtcnt;						//옥내_기계식_대수(대)
	String indrMechArea;						//옥내_기계식_면적(㎡)
	String oudrMechUtcnt;						//옥외_기계식_대수(대)
	String oudrMechArea;						//옥외_기계식_면적(㎡)
	String indrAutoUtcnt;						//옥내_자주식_대수(대)
	String indrAutoArea;						//옥내_자주식_면적(㎡)
	String oudrAutoUtcnt;						//옥외_자주식_대수(대)
	String oudrAutoArea;						//옥외_자주식_면적(㎡)
	String pmsDay;								//허가_일
	String stcnsDay;							//착공_일
	String useAprDay;							//사용승인_일
	String pmsnoYear;							//허가번호_년
	String pmsnoKikCd;							//허가번호_기관_코드
	String pmsnoKikCdNm;						//허가번호_기관_코드_명
	String pmsnoGbCd;							//허가번호_구분_코드
	String pmsnoGbCdNm;							//허가번호_구분_코드_명
	String hoCnt;								//호_수(호)
	String engrGrade;							//에너지효율_등급
	String engrRat;								//에너지절감_율
	String engrEpi;								//에너지_EPI점수
	String gnBldGrade;							//친환경_건축물_등급
	String gnBldCert;							//친환경_건축물_인증점수
	String itgBldGrade;							//지능형_건축물_등급
	String itgBldCert;							//지능형_건축물_인증점수
	String crtnDay;								//생성_일자
	String rserthqkDsgnApplyYn;					//내진_설계_적용_여부
	String rserthqkAblty;						//내진_능력
}
